// const cacheName = "Si Hajar"
// const preCache = ["/", "/index.php", "/user.php", "/assets/js/plugin/webfont/webfont.min.js",
//           "/assets/css/fonts.min.css",
//           "/assets/css/bootstrap.min.css",
//           "/assets/css/plugins.min.css",
//           "/assets/css/kaiadmin.min.css",
//           "/assets/css/demo.css",
//           "/assets/js/plugin/webfont/webfont.min.js",
//           "/assets/js/setting-demo.js",
//           "/assets/js/demo.js",
//           "/assets/js/core/jquery-3.7.1.min.js",
//           "/assets/js/core/popper.min.js",
//           "/assets/js/core/bootstrap.min.js",
//           "/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js",
//           "/assets/js/plugin/chart.js/chart.min.js",
//           "/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js",
//           "/assets/js/plugin/chart-circle/circles.min.js",
//           "/assets/js/plugin/datatables/datatables.min.js",
//           "/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js",
//           "/assets/js/plugin/jsvectormap/jsvectormap.min.js",
//           "/assets/js/plugin/jsvectormap/world.js",
//           "/assets/js/plugin/sweetalert/sweetalert.min.js",
//           "/login.php",
//           "/assets/css/login.css",
//           "/assets/js/script.js",
//           "/assets/css/datatables.min.css",
//           "/assets/js/setting-demo2.js",
//           "/pages_admin/add-xdkv1.php",
//           "/pages_admin/add-xdkv2.php",
//           "/pages_admin/add-xdkv3.php",
//           "/pages_admin/add-xidkv1.php",
//           "/pages_admin/add-xidkv2.php",
//           "/pages_admin/add-xidkv3.php",
//           "/pages_admin/add-xiidkv1.php",
//           "/pages_admin/add-xiidkv2.php",
//           "/pages_admin/add-xiidkv3.php",
//           "/pages_admin/add-xiisija1.php",
//           "/pages_admin/add-xiisija2.php",
//           "/pages_admin/add-xisija1.php",
//           "/pages_admin/add-xsija1.php",
//           "/pages_admin/add-xsija2.php",
//           "/pages_admin/belumabsenxdkv2.php",
//           "/pages_admin/belumabsenxdkv3.php",
//           "/pages_admin/belumabsenxidkv1.php",
//           "/pages_admin/belumabsenxidkv2.php",
//           "/pages_admin/belumabsenxidkv3.php",
//           "/pages_admin/belumabsenxiidkv1.php",
//           "/pages_admin/belumabsenxiidkv2.php",
//           "/pages_admin/belumabsenxiidkv3.php",
//           "/pages_admin/belumabsenxdkv1.php",
//           "/pages_users/belumabsenxdkv1.php",
//           "/pages_users/belumabsenxdkv2.php",
//           "/pages_users/belumabsenxdkv3.php",
//           "/pages_users/belumabsenxidkv1.php",
//           "/pages_users/belumabsenxidkv2.php",
//           "/pages_users/belumabsenxidkv3.php",
//           "/pages_users/belumabsenxiidkv1.php",
//           "/pages_users/belumabsenxiidkv2.php",
//           "/pages_users/belumabsenxiidkv3.php",
//           "/pages_users/belumabsenxiisija1.php",
//           "/pages_admin/belumabsenxiisija1.php",
//           "/pages_admin/belumabsenxiisija2.php",
//           "/pages_users/belumabsenxiisija2.php",
//           "/pages_admin/belumabsenxisija1.php",
//           "/pages_users/belumabsenxisija1.php",
//           "/pages_admin/belumabsenxsija1.php",
//           "/pages_users/belumabsenxsija1.php",
//           "/pages_admin/belumabsenxsija2.php",
//           "/pages_users/belumabsenxsija2.php",
//           "/pages_admin/data-absen-dkv.php",
//           "/pages_admin/data-absen-lpb.php",
//           "/pages_admin/data-absen-sija.php",
//           "/pages_users/data-absen-sija.php",
//           "/pages_users/data-absen-dkv.php",
//           "/pages_admin/data-dkv.php",
//           "/pages_admin/data-lpb.php",
//           "/pages_admin/data-sija.php",
//           "/pages_users/data-sija.php",
//           "/pages_users/data-dkv.php",
//           "/pages_users/dataabsenxiidkv1.php",
//           "/pages_users/dataabsenxiidkv2.php",
//           "/pages_users/dataabsenxiidkv3.php",
//           "/pages_users/dataabsenxidkv1.php",
//           "/pages_users/dataabsenxidkv2.php",
//           "/pages_users/dataabsenxidkv3.php",
//           "/pages_users/dataabsenxdkv1.php",
//           "/pages_users/dataabsenxdkv2.php",
//           "/pages_users/dataabsenxdkv3.php",
//           "/pages_admin/dataabsenxiidkv1.php",
//           "/pages_admin/dataabsenxiidkv2.php",
//           "/pages_admin/dataabsenxiidkv3.php",
//           "/pages_admin/dataabsenxidkv1.php",
//           "/pages_admin/dataabsenxidkv2.php",
//           "/pages_admin/dataabsenxidkv3.php",
//           "/pages_admin/dataabsenxdkv1.php",
//           "/pages_admin/dataabsenxdkv2.php",
//           "/pages_admin/dataabsenxdkv3.php",
//           "/pages_admin/dataabsenxiisija1.php",
//           "/pages_users/dataabsenxiisija1.php",
//           "/pages_admin/dataabsenxiisija2.php",
//           "/pages_users/dataabsenxiisija2.php",
//           "/pages_admin/dataabsenxisija1.php",
//           "/pages_users/dataabsenxisija1.php",
//           "/pages_admin/dataabsenxsija1.php",
//           "/pages_users/dataabsenxsija1.php",
//           "/pages_admin/dataabsenxsija2.php",
//           "/pages_users/dataabsenxsija2.php",
//           "/pages_admin/dataxdkv1.php",
//           "/pages_admin/dataxdkv2.php",
//           "/pages_admin/dataxdkv3.php",
//           "/pages_admin/dataxidkv1.php",
//           "/pages_admin/dataxidkv2.php",
//           "/pages_admin/dataxidkv3.php",
//           "/pages_admin/dataxiidkv1.php",
//           "/pages_admin/dataxiidkv2.php",
//           "/pages_admin/dataxiidkv3.php",
//           "/pages_users/dataxiidkv1.php",
//           "/pages_users/dataxiidkv2.php",
//           "/pages_users/dataxiidkv3.php",
//           "/pages_users/dataxidkv1.php",
//           "/pages_users/dataxidkv2.php",
//           "/pages_users/dataxidkv3.php",
//           "/pages_users/dataxdkv1.php",
//           "/pages_users/dataxdkv2.php",
//           "/pages_users/dataxdkv3.php",
//           "/pages_users/dataxiisija1.php",
//           "/pages_users/dataxiisija2.php",
//           "/pages_admin/dataxiisija1.php",
//           "/pages_admin/dataxiisija2.php",
//           "/pages_users/dataxisija1.php",
//           "/pages_admin/dataxisija1.php",
//           "/pages_users/dataxsija1.php",
//           "/pages_users/dataxsija2.php",
//           "/pages_admin/dataxsija1.php",
//           "/pages_admin/dataxsija2.php",
//           "/pages_admin/edit-xdkv1.php",
//           "/pages_admin/edit-xdkv2.php",
//           "/pages_admin/edit-xdkv3.php",
//           "/pages_admin/edit-xidkv1.php",
//           "/pages_admin/edit-xidkv2.php",
//           "/pages_admin/edit-xidkv3.php",
//           "/pages_admin/edit-xiidkv1.php",
//           "/pages_admin/edit-xiidkv2.php",
//           "/pages_admin/edit-xiidkv3.php",
//           "/pages_admin/edit-xiisija1.php",
//           "/pages_admin/edit-xiisija2.php",
//           "/pages_admin/edit-xisija1.php",
//           "/pages_admin/edit-xsija1.php",
//           "/pages_admin/edit-xsija2.php",
//           "/export/export-absenxiidkv1.php",
//           "/export/export-absenxiidkv2.php",
//           "/export/export-absenxiidkv3.php",
//           "/export/export-absenxidkv1.php",
//           "/export/export-absenxidkv2.php",
//           "/export/export-absenxidkv3.php",
//           "/export/export-absenxdkv1.php",
//           "/export/export-absenxdkv2.php",
//           "/export/export-absenxdkv3.php",
//           "/export/export-absenxiisija1.php",
//           "/export/export-absenxiisija2.php",
//           "/export/export-absenxisija1.php",
//           "/export/export-absenxsija1.php",
//           "/export/export-absenxsija2.php",
//           "/export/export-belumabsenxiidkv1.php",
//           "/export/export-belumabsenxiidkv2.php",
//           "/export/export-belumabsenxiidkv3.php",
//           "/export/export-belumabsenxidkv1.php",
//           "/export/export-belumabsenxidkv2.php",
//           "/export/export-belumabsenxidkv3.php",
//           "/export/export-belumabsenxdkv1.php",
//           "/export/export-belumabsenxdkv2.php",
//           "/export/export-belumabsenxdkv3.php",
//           "/export/export-belumabsenxiisija1.php",
//           "/export/export-belumabsenxiisija2.php",
//           "/export/export-belumabsenxisija1.php",
//           "/export/export-belumabsenxsija1.php",
//           "/export/export-belumabsenxsija2.php",
//           "/export/export-xdkv1.php",
//           "/export/export-xdkv2.php",
//           "/export/export-xdkv3.php",
//           "/export/export-xidkv1.php",
//           "/export/export-xidkv2.php",
//           "/export/export-xidkv3.php",
//           "/export/export-xiidkv1.php",
//           "/export/export-xiidkv2.php",
//           "/export/export-xiidkv3.php",
//           "/export/export-xiisija1.php",
//           "/export/export-xiisija2.php",
//           "/export/export-xisija1.php",
//           "/export/export-xsija1.php",
//           "/export/export-xsija2.php",
//           "/pages_admin/log-lpb.php",
//           "/pages_admin/log-sija.php",
//           "/pages_users/log-sija.php",
//           "/pages_users/log.dkv.php",
//           "/pages_admin/log.dkv.php"]

// self.addEventListener("install", () => {
//     console.log("service worker installed")

//     e.waitUntil(
//         (async () => {
//             const cache = await caches.open(cacheName)
//             cache.addAll(preCache)
//         })(),
//     )
// })

// self.addEventListener("fetch", (e) => {
//     e.respondWith((async () => {
//         const cache = await caches.open(cacheName)
//         const resCache = await cache.match(e.request)

//         if (resCache) return resCache

//         try {
//             const res = await fetch(e.request)

//             cache.put(e.request, res.clone())
//             return res
//         } catch (error) {
//             console.log(error)
//         }
//     })(),
//     )
// })